/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedSharesRouteImport } from './routes/_authenticated/shares'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPresetsRouteImport } from './routes/_authenticated/presets'
import { Route as AuthenticatedOracleRouteImport } from './routes/_authenticated/oracle'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedGlobeRouteImport } from './routes/_authenticated/globe'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBriefingRouteImport } from './routes/_authenticated/briefing'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as ApiPublicHooksRunAutomationsRouteImport } from './routes/api/public/hooks/run-automations'
import { Route as ApiPublicHooksRefreshWidgetsRouteImport } from './routes/api/public/hooks/refresh-widgets'
import { Route as ApiPublicHooksDeviceIngestRouteImport } from './routes/api/public/hooks/device-ingest'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSharesRoute = AuthenticatedSharesRouteImport.update({
  id: '/shares',
  path: '/shares',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPresetsRoute = AuthenticatedPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOracleRoute = AuthenticatedOracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGlobeRoute = AuthenticatedGlobeRouteImport.update({
  id: '/globe',
  path: '/globe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBriefingRoute = AuthenticatedBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksRunAutomationsRoute =
  ApiPublicHooksRunAutomationsRouteImport.update({
    id: '/api/public/hooks/run-automations',
    path: '/api/public/hooks/run-automations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshWidgetsRoute =
  ApiPublicHooksRefreshWidgetsRouteImport.update({
    id: '/api/public/hooks/refresh-widgets',
    path: '/api/public/hooks/refresh-widgets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDeviceIngestRoute =
  ApiPublicHooksDeviceIngestRouteImport.update({
    id: '/api/public/hooks/device-ingest',
    path: '/api/public/hooks/device-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/globe': typeof AuthenticatedGlobeRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/oracle': typeof AuthenticatedOracleRoute
  '/presets': typeof AuthenticatedPresetsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shares': typeof AuthenticatedSharesRoute
  '/s/$slug': typeof SSlugRoute
  '/api/public/hooks/device-ingest': typeof ApiPublicHooksDeviceIngestRoute
  '/api/public/hooks/refresh-widgets': typeof ApiPublicHooksRefreshWidgetsRoute
  '/api/public/hooks/run-automations': typeof ApiPublicHooksRunAutomationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/globe': typeof AuthenticatedGlobeRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/oracle': typeof AuthenticatedOracleRoute
  '/presets': typeof AuthenticatedPresetsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shares': typeof AuthenticatedSharesRoute
  '/s/$slug': typeof SSlugRoute
  '/api/public/hooks/device-ingest': typeof ApiPublicHooksDeviceIngestRoute
  '/api/public/hooks/refresh-widgets': typeof ApiPublicHooksRefreshWidgetsRoute
  '/api/public/hooks/run-automations': typeof ApiPublicHooksRunAutomationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/briefing': typeof AuthenticatedBriefingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/globe': typeof AuthenticatedGlobeRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/oracle': typeof AuthenticatedOracleRoute
  '/_authenticated/presets': typeof AuthenticatedPresetsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shares': typeof AuthenticatedSharesRoute
  '/s/$slug': typeof SSlugRoute
  '/api/public/hooks/device-ingest': typeof ApiPublicHooksDeviceIngestRoute
  '/api/public/hooks/refresh-widgets': typeof ApiPublicHooksRefreshWidgetsRoute
  '/api/public/hooks/run-automations': typeof ApiPublicHooksRunAutomationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/achievements'
    | '/agents'
    | '/alerts'
    | '/automations'
    | '/briefing'
    | '/dashboard'
    | '/devices'
    | '/globe'
    | '/history'
    | '/oracle'
    | '/presets'
    | '/settings'
    | '/shares'
    | '/s/$slug'
    | '/api/public/hooks/device-ingest'
    | '/api/public/hooks/refresh-widgets'
    | '/api/public/hooks/run-automations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/achievements'
    | '/agents'
    | '/alerts'
    | '/automations'
    | '/briefing'
    | '/dashboard'
    | '/devices'
    | '/globe'
    | '/history'
    | '/oracle'
    | '/presets'
    | '/settings'
    | '/shares'
    | '/s/$slug'
    | '/api/public/hooks/device-ingest'
    | '/api/public/hooks/refresh-widgets'
    | '/api/public/hooks/run-automations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/achievements'
    | '/_authenticated/agents'
    | '/_authenticated/alerts'
    | '/_authenticated/automations'
    | '/_authenticated/briefing'
    | '/_authenticated/dashboard'
    | '/_authenticated/devices'
    | '/_authenticated/globe'
    | '/_authenticated/history'
    | '/_authenticated/oracle'
    | '/_authenticated/presets'
    | '/_authenticated/settings'
    | '/_authenticated/shares'
    | '/s/$slug'
    | '/api/public/hooks/device-ingest'
    | '/api/public/hooks/refresh-widgets'
    | '/api/public/hooks/run-automations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SSlugRoute: typeof SSlugRoute
  ApiPublicHooksDeviceIngestRoute: typeof ApiPublicHooksDeviceIngestRoute
  ApiPublicHooksRefreshWidgetsRoute: typeof ApiPublicHooksRefreshWidgetsRoute
  ApiPublicHooksRunAutomationsRoute: typeof ApiPublicHooksRunAutomationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shares': {
      id: '/_authenticated/shares'
      path: '/shares'
      fullPath: '/shares'
      preLoaderRoute: typeof AuthenticatedSharesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presets': {
      id: '/_authenticated/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof AuthenticatedPresetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oracle': {
      id: '/_authenticated/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof AuthenticatedOracleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/globe': {
      id: '/_authenticated/globe'
      path: '/globe'
      fullPath: '/globe'
      preLoaderRoute: typeof AuthenticatedGlobeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/briefing': {
      id: '/_authenticated/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof AuthenticatedBriefingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/run-automations': {
      id: '/api/public/hooks/run-automations'
      path: '/api/public/hooks/run-automations'
      fullPath: '/api/public/hooks/run-automations'
      preLoaderRoute: typeof ApiPublicHooksRunAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-widgets': {
      id: '/api/public/hooks/refresh-widgets'
      path: '/api/public/hooks/refresh-widgets'
      fullPath: '/api/public/hooks/refresh-widgets'
      preLoaderRoute: typeof ApiPublicHooksRefreshWidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/device-ingest': {
      id: '/api/public/hooks/device-ingest'
      path: '/api/public/hooks/device-ingest'
      fullPath: '/api/public/hooks/device-ingest'
      preLoaderRoute: typeof ApiPublicHooksDeviceIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedBriefingRoute: typeof AuthenticatedBriefingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedGlobeRoute: typeof AuthenticatedGlobeRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedOracleRoute: typeof AuthenticatedOracleRoute
  AuthenticatedPresetsRoute: typeof AuthenticatedPresetsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSharesRoute: typeof AuthenticatedSharesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedBriefingRoute: AuthenticatedBriefingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedGlobeRoute: AuthenticatedGlobeRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedOracleRoute: AuthenticatedOracleRoute,
  AuthenticatedPresetsRoute: AuthenticatedPresetsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSharesRoute: AuthenticatedSharesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SSlugRoute: SSlugRoute,
  ApiPublicHooksDeviceIngestRoute: ApiPublicHooksDeviceIngestRoute,
  ApiPublicHooksRefreshWidgetsRoute: ApiPublicHooksRefreshWidgetsRoute,
  ApiPublicHooksRunAutomationsRoute: ApiPublicHooksRunAutomationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
